FROM ubuntu:24.04 AS sources

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app


RUN apt update
RUN apt install --no-install-recommends -y  wget unzip apt-transport-https ca-certificates

RUN wget https://ton-blockchain.github.io/global.config.json
RUN wget https://github.com/ton-blockchain/ton/releases/download/v2024.06/ton-linux-x86_64.zip
RUN unzip ton-linux-x86_64.zip
RUN chmod +x generate-random-id rldp-http-proxy

RUN ls -la


# run section
FROM ubuntu:24.04
WORKDIR /opt/ton-proxy
COPY --from=sources /app/generate-random-id /usr/local/bin
COPY --from=sources /app/rldp-http-proxy /usr/local/bin
COPY --from=sources /app/global.config.json /opt/ton-proxy/global.config.json

EXPOSE 8080
CMD ["rldp-http-proxy"]