# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: build app

on:
  push:
    branches:
      - '**' # only for debug
#      - "main"
#      - "master"
    tags:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest

    env:  # set global vas
      DOCKER_REPO: tonstakers/ton-proxy
      DOCKER_FILE: docker-ton-proxy.ci
      UBUNTU_IMAGE_VERSION: "24.04"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version
        id: vars
        run: |
          echo "TON_PROXY_VERSION=$(cat ton-repo-release.txt)"
          echo "TON_PROXY_VERSION=$(cat ton-repo-release.txt)" >> $GITHUB_ENV
          echo "TIMESTAMP=$(date -u +%Y%m%d%H%M%S)" >> $GITHUB_ENV


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ${{ env.DOCKER_FILE }}
          push: true
          tags: | 
            ${{ env.DOCKER_REPO }}:${{ env.TON_PROXY_VERSION }}
            ${{ env.DOCKER_REPO }}:latest
          build-args: |
            TIMESTAMP=${{ env.TIMESTAMP }}
            TON_PROXY_VERSION=${{ env.TON_PROXY_VERSION }}
